USE [master]
GO

/****** Object:  Database [CatalogueSystemDB]    Script Date: 19.1.2015 г. 14:24:20 ******/
CREATE DATABASE [CatalogueSystemDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CatalogueSystemDB', FILENAME = N'E:\Microsoft SQL Server 2014\MSSQL12.SQL2014\MSSQL\DATA\CatalogueSystemDB.mdf' , SIZE = 19456KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CatalogueSystemDB_log', FILENAME = N'E:\Microsoft SQL Server 2014\MSSQL12.SQL2014\MSSQL\DATA\CatalogueSystemDB_log.ldf' , SIZE = 6272KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CatalogueSystemDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CatalogueSystemDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CatalogueSystemDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CatalogueSystemDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CatalogueSystemDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CatalogueSystemDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CatalogueSystemDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET RECOVERY FULL 
GO

ALTER DATABASE [CatalogueSystemDB] SET  MULTI_USER 
GO

ALTER DATABASE [CatalogueSystemDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CatalogueSystemDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CatalogueSystemDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CatalogueSystemDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CatalogueSystemDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CatalogueSystemDB] SET  READ_WRITE 
GO

